- hosts: localhost
  vars_prompt:
    - name: container_name
      prompt: "Container Name?"
      private: no
  
  tasks:

  - name: sdk install
    command: "pip3 install docker"
  
  - name: Build an image and push
    docker_image:
      build:
        path: ./ubuntussh
      name: sardine123/ubuntussh
      tag: latest
      force_source: yes
      push: no
      source: build
 
  - name: Launch docker container with ssh enabled image
    docker_container:
      name: "{{ container_name }}"
      image: sardine123/ubuntussh:latest
      interactive: yes
      tty: yes
      detach: yes
      state: started

  - name: Get info of the container
    docker_container_info:
      name: "{{ container_name }}" 
    register: result

  - name: Printing IP Address
    debug:
            msg: "{{ result.container.NetworkSettings.IPAddress }}"

  - name: Update Container IP in inventory
    blockinfile:
      path: inventory
      block: |
              [docker]
              {{ result.container.NetworkSettings.IPAddress }} ansible_user=builder ansible_password=builder ansible_connection=ssh
