- hosts: docker
  vars_prompt:
    - name: gpg_pass
      prompt: "GPG Key passphrase?"
      private: yes

  vars:
    - gpg_key: "{{ lookup('file', './kavplex.gpg') }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: "Add makedeb PPA"
    apt_repository:
      repo: ppa:sardine123/makedeb
      state: present

  - name: "Installing packages"
    package:
        name: "{{ item }}"
        state: present
    loop:
      - git
      - gnupg
      - pbuilder
      - ubuntu-dev-tools
      - apt-file
      - python3
      - python3-pip
      - debhelper
      - asciidoctor
      - makedeb-makepkg
      - jq
  - name: "Install packaging module"
    command: "pip3 install packaging"

  - name: "Import GPG key"
    gpg_key:
      content: "{{ gpg_key }}"

